#!/bin/bash

echo -en "Enter Distinguished Name (ex. /C=CA/O=Grid/OU=phys.uvic.ca/CN=Colson Driemel)\n > "
echo -en "Enter Common Name from your certificate\n (ex. /C=CA/O=Grid/OU=phys.uvic.ca/CN=Colson Driemel would be Colson Driemel)\n > "
read commonname

echo -en "Updating database... \n"
sqlite3 /etc/glintv2/db.sqlite3 "Update auth_user SET is_superuser='1' where username='$commonname'"
sqlite3 /etc/glintv2/db.sqlite3 "Update auth_user SET is_staff='1' where username='$commonname'"

echo -en "Database updated...\n"