# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glint_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('authentication_method', models.CharField(default='x509', max_length=32)),
                ('common_name', models.CharField(default='', max_length=64)),
                ('distinguished_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32)),
                ('uri', models.CharField(default='', max_length=256)),
                ('tenant', models.CharField(default='', max_length=128)),
                ('username', models.CharField(default='', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32)),
                ('last_used', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Glint_User')),
            ],
        ),
    ]
