# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_projects',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glintwebui.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_projects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Project'),
        ),
    ]
