# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='uri',
            new_name='auth_url',
        ),
        migrations.AddField(
            model_name='project',
            name='tenant_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
