# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0002_auto_20170124_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Glint_User',
        ),
    ]
