# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0003_remove_project_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='glint_user',
            name='active_project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Project'),
        ),
    ]
