# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0004_glint_user_active_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glint_user',
            name='active_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Project'),
        ),
    ]
