# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0007_auto_20170307_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glint_user',
            name='active_project',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
