# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0009_auto_20170317_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='unique_id',
            new_name='proj_id',
        ),
    ]
