# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0010_auto_20170317_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used', models.DateTimeField()),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glintwebui.Glint_User')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_projects',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Projects',
        ),
    ]
