# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0011_auto_20170323_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.CharField(default='', max_length=64),
        ),
    ]
