# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0012_project_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glint_user',
            name='distinguished_name',
            field=models.CharField(max_length=128),
        ),
    ]
