# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0014_auto_20170331_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alias',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
