# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glintwebui', '0015_auto_20170407_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alias',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
